## CS231n Numpy Practice  

#### Array

In [22]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0][0])
print(b[0,0])

a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,2),5)
print(c)

d = np.eye(3) # Create Identity matrix
print(d)

e = np.random.random((2,2))
print(e)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1
1
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.83189636 0.52714748]
 [0.25556207 0.27622196]]


#### Array indexing

In [30]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b = a[:2,1:3]  # first 2 row , and colums 1, 2
print(b)

c = a[:1,1:3]
print(c)

row_r1 = a[1,:] # rank (4,)
print(row_r1, row_r1.shape)
row_r2 = a[1:2,:] # rank (1,4)
print(row_r2, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2 3]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [50]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,2],[0,0,0]])
print(a[[0,1,2],[1,1,1]])
print(a[[0,1,2],[0,1,0]]) # prints "[1 4 5]"

print(np.array([a[0,0], a[1,1], a[2,0]]))

print(a[[0,0],[1,1]])
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 3 5]
[2 4 6]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [60]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b = np.array([0,2,0,1])
print(a[np.arange(4), b])

a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [63]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a > 2)

print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
