## CS231n Numpy Practice  

#### Array

In [22]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0][0])
print(b[0,0])

a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,2),5)
print(c)

d = np.eye(3) # Create Identity matrix
print(d)

e = np.random.random((2,2))
print(e)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1
1
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.83189636 0.52714748]
 [0.25556207 0.27622196]]


#### Array indexing

In [30]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

b = a[:2,1:3]  # first 2 row , and colums 1, 2
print(b)

c = a[:1,1:3]
print(c)

row_r1 = a[1,:] # rank (4,)
print(row_r1, row_r1.shape)
row_r2 = a[1:2,:] # rank (1,4)
print(row_r2, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2 3]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [50]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,2],[0,0,0]])
print(a[[0,1,2],[1,1,1]])
print(a[[0,1,2],[0,1,0]]) # prints "[1 4 5]"

print(np.array([a[0,0], a[1,1], a[2,0]]))

print(a[[0,0],[1,1]])
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 3 5]
[2 4 6]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [60]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b = np.array([0,2,0,1])
print(a[np.arange(4), b])

a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [64]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a > 2)

print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


#### Datatypes

In [69]:
import numpy as np

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


#### Array math

In [76]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

print(x + y)
print(np.add(x,y))

print(x - y)
print(np.subtract(x,y))

print(x * y)
print(np.multiply(x,y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [79]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x,v))

print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [80]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [82]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


#### Broadcasting 

In [87]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

print(x)
print(v)
print(y)

for i in range(4):
    y[i,:] = x[i, :] + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [96]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4,1))

print(x)
print(vv)

y = x + vv
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
